{% set name = "lfdfiles" %}
{% set version = "2025.9.17" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lfdfiles-{{ version }}.tar.gz
  sha256: 17bffd96e709abc3741f202ff57f3fb93481f32380f56790d52c1a12f61e662c

build:
  skip: true  # [py<311]
  entry_points:
    - lfdfiles = lfdfiles.__main__:main
    - fbd2b64 = lfdfiles.fbd2b64:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.1.0                         # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
  host:
    - cython >=3.1.0
    - numpy
    - pip
    - python
    - setuptools
  run:
    - click
    - czifile
    - imagecodecs
    - matplotlib-base
    - netpbmfile
    - oiffile
    - python
    - tifffile

test:
  imports:
    - lfdfiles
  commands:
    - pip list
    - pip check
    - lfdfiles --help
    - fbd2b64 --help
  requires:
    - pip

about:
  home: https://www.cgohlke.com
  summary: Laboratory for Fluorescence Dynamics (LFD) file formats
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/cgohlke/lfdfiles/

extra:
  recipe-maintainers:
    - goanpeca
    - cgohlke
