{% set name = "lfdfiles" %}
{% set version = "2026.1.14" %}
{% set sha256 = "62f0ecd185a0ac99131e08f0a54d4a88b381b41b92c5b0cef244a937b71b26ef" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python
  entry_points:
    - lfdfiles = lfdfiles.lfdfiles:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy
    - click
    - czifile
    - fbdfile
    - imagecodecs
    - matplotlib-base
    - netpbmfile
    - oiffile
    - python >={{ python_min }}
    - tifffile

test:
  imports:
    - lfdfiles
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.cgohlke.com
  summary: Laboratory for Fluorescence Dynamics (LFD) file formats
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    Lfdfiles is a Python library and console script for reading, writing, converting, and viewing many of the proprietary file formats used to store experimental data and metadata at the Laboratory for Fluorescence Dynamics.
  dev_url: https://github.com/cgohlke/lfdfiles

extra:
  recipe-maintainers:
    - goanpeca
    - cgohlke
