{% set name = "lfdfiles" %}
{% set version = "2023.9.16" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lfdfiles-{{ version }}.tar.gz
  sha256: ebbb11baf0ddd6ae4182b7303d517944d1896b88f2f601fb096251b65e31ea5a

build:
  number: 0
  skip: true  # [py<39]
  entry_points:
    - lfdfiles = lfdfiles.__main__:main
    - fbd2b64 = lfdfiles.fbd2b64:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
  host:
    - cython >=0.29.27
    - numpy >=1.21.5
    - pip
    - python
    - setuptools
  run:
    - click
    - czifile
    - imagecodecs
    - matplotlib-base
    - netpbmfile
    - {{ pin_compatible('numpy') }}
    - oiffile
    - python
    - tifffile

test:
  imports:
    - lfdfiles
  commands:
    - pip list
    - pip check
    - lfdfiles --help
    - fbd2b64 --help
  requires:
    - pip

about:
  home: https://www.lfd.uci.edu/~gohlke/
  summary: Laboratory for Fluorescence Dynamics (LFD) file formats
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/cgohlke/lfdfiles/

extra:
  recipe-maintainers:
    - goanpeca
